# Generated by Django 5.1.4 on 2024-12-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slides/')),
                ('button_text1', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link1', models.URLField(blank=True, null=True)),
                ('button_text2', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link2', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
