# Generated by Django 5.0.4 on 2024-12-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='button_link1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='button_link2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='button_text1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='button_text2',
        ),
    ]
