# Generated by Django 5.0.4 on 2024-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_slide_button_link1_remove_slide_button_link2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
    ]
