# Generated by Django 5.0.4 on 2024-12-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_slide_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
